version: "2.3"

services:
    service_template-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/service_template/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/service_template:rw
        ports:
          - 8082:8080
        working_dir: /service_template
        entrypoint: >
          ./tests/run_as_user.sh
          ./build_release/service_template
          --config ./configs/static_config.yaml
          --config_vars ./configs/config_vars.yaml


    service_template-build:
      image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
      privileged: true
      environment:
        - PREFIX=${PREFIX:-~/.local}
        - CCACHE_DIR=/service_template/.ccache
        - CORES_DIR=/cores
      volumes:
        - .:/service_template:rw
      working_dir: /service_template
      entrypoint: >
        ./tests/run_as_user.sh
        make build-release